print("Welcome to MAAI Workshop")
print("Please write your name here Victoria")
print("Please write your name here Santiago Sierra Ibañez")
print("mis bros, que son tus comidas favoritas?")
print("OLE, ole, oleoleole. LUCHO Diaz LUCHOOO")
print("Hola, soy Victoria y me gusta la pizza de pepperoni con coca cola fría un sábado en la noche viendo piratas del caribe")
print("Hola, soy Santiago y me gusta la pizza hawaiana de pizza hut con coca cola fría un sábado en la noche viendo harry potter") 