print("Welcome to MAAI Workshop")
print("Please write your name here Victoria")
print("Please write your name here Santiago Sierra Ibañez")
print("mis bros, que son tus comidas favoritas?")
print("OLE, ole, oleoleole. LUCHO Diaz LUCHOOO")
